'use client'

import { useEffect, useMemo, useRef, useState } from 'react'
import { ArrowLeft, ArrowRight, Check, ChevronLeft, ChevronRight, CircleHelp, Minus, Plus, Radio, RotateCcw, ScanLine, ShoppingBasket, Sparkles, Trash2, TriangleAlert, Users, UserRound } from 'lucide-react'
import { AndroidAppLink } from '@/components/android-app-link'
import { BarcodeScanner, primeScannerFeedback } from '@/components/barcode-scanner'
import { FinishCelebration } from '@/components/finish-celebration'
import { lookupProduct, NUTRIENTS, productKey, type CartItem, type Product } from '@/lib/products'

type Mode = 'individual' | 'family'
type Cadence = 'weekly' | 'monthly'
type Member = { id: number; name: string; age: number; type: 'Adult' | 'Child'; gender: 'Female' | 'Male'; height: number; weight: number; sizeStep: number }

const PRODUCTS: Product[] = [
  { id: 1, name: 'Garden eggs', category: 'Produce', calories: 80, protein: 6, carbs: 18, fat: 1, fiber: 5, accent: '#86b883' },
  { id: 2, name: 'Golden oats', category: 'Grains', calories: 190, protein: 7, carbs: 32, fat: 4, fiber: 5, accent: '#d6a95c' },
  { id: 3, name: 'Greek yogurt', category: 'Dairy', calories: 140, protein: 15, carbs: 8, fat: 5, fiber: 0, accent: '#b3c8d8' },
  { id: 4, name: 'Red lentils', category: 'Pantry', calories: 210, protein: 14, carbs: 34, fat: 1, fiber: 12, accent: '#d47c58' },
  { id: 5, name: 'Avocado', category: 'Produce', calories: 160, protein: 2, carbs: 9, fat: 15, fiber: 7, accent: '#9bbd65' },
]

const initialMember: Member = { id: 1, name: 'You', age: 30, type: 'Adult', gender: 'Female', height: 170, weight: 65, sizeStep: 3 }
const SILHOUETTE_LEVELS = ['slim', 'lean', 'average', 'fuller', 'heavy'] as const
function silhouetteCategory(member: Member) { return member.type === 'Child' ? 'child' : member.gender.toLowerCase() }
function Silhouette({ member, small = false }: { member: Member; small?: boolean }) { const category = silhouetteCategory(member); const level = SILHOUETTE_LEVELS[member.sizeStep - 1] || 'average'; return <><img className={`silhouette-image ${small ? 'small' : ''}`} src={`/silhouettes/${category}_${member.sizeStep}_${level}.svg`} alt={`${member.name} ${level} body silhouette`} onError={e => { e.currentTarget.style.display = 'none'; e.currentTarget.nextElementSibling?.classList.add('visible') }} /><div className="silhouette-fallback" aria-hidden="true"><div className="sil-head" /><div className="sil-body" /><div className="sil-legs" /></div></> }
const emptyTargets = { calories: 0, protein: 0, carbs: 0, fat: 0, fiber: 0 }

function Logo() { return <div className="brand"><div className="brand-mark"><ShoppingBasket size={22} strokeWidth={2.5} /></div><span>NutriCart</span></div> }
function Stepper({ step }: { step: number }) { return <div className="stepper" aria-label={`Step ${step} of 3`}>{['Household', 'Your people', 'Your cart'].map((label, i) => <div className={`step ${step >= i + 1 ? 'active' : ''}`} key={label}><span>{step > i + 1 ? <Check size={13} /> : i + 1}</span><small>{label}</small></div>)}</div> }
function PersonIcon({ family = false }: { family?: boolean }) { return <div className={`person-icon ${family ? 'family-icon' : ''}`}><UserRound className="person-back" /><UserRound className="person-front" /></div> }
function ProgressBar({ value, color = 'green' }: { value: number; color?: string }) { return <div className="progress-track"><div className={`progress-fill ${color}`} style={{ width: `${Math.min(100, value)}%` }} /></div> }

export default function Page() {
  const [screen, setScreen] = useState<'mode' | 'count' | 'profiles' | 'calculating' | 'cart'>('mode')
  const [mode, setMode] = useState<Mode | null>(null)
  const [cadence, setCadence] = useState<Cadence | null>(null)
  const [count, setCount] = useState(2)
  const [members, setMembers] = useState<Member[]>([initialMember])
  const [activeMember, setActiveMember] = useState(0)
  const [cart, setCart] = useState<CartItem[]>([])
  const [toast, setToast] = useState<{ text: string; tone: 'ok' | 'warn' } | null>(null)
  const [scannerOpen, setScannerOpen] = useState(false)
  const [celebrating, setCelebrating] = useState(false)
  const toastTimer = useRef<number | undefined>(undefined)

  const targets = useMemo(() => { const days = cadence === 'monthly' ? 30 : 7; return members.reduce((sum, member) => { const factor = (member.type === 'Child' ? 0.72 : 1) * days; sum.calories += Math.round((member.gender === 'Male' ? 2400 : 2000) * factor); sum.protein += Math.round(60 * factor); sum.carbs += Math.round(250 * factor); sum.fat += Math.round(70 * factor); sum.fiber += Math.round(28 * factor); return sum }, { ...emptyTargets }) }, [members, cadence])
  const consumed = useMemo(() => cart.reduce((sum, item) => { sum.calories += item.calories * item.quantity; sum.protein += item.protein * item.quantity; sum.carbs += item.carbs * item.quantity; sum.fat += item.fat * item.quantity; sum.fiber += item.fiber * item.quantity; return sum }, { ...emptyTargets }), [cart])
  const current = members[activeMember] || initialMember

  // USB/Bluetooth barcode guns act as keyboards: digits arrive a few ms apart, then Enter.
  useEffect(() => { if (screen !== 'cart' || scannerOpen) return; let buffer = ''; let lastKey = 0; function onKey(e: KeyboardEvent) { const target = e.target as HTMLElement; if (target.closest('input, textarea, [contenteditable]')) return; const now = performance.now(); if (now - lastKey > 60) buffer = ''; lastKey = now; if (/^\d$/.test(e.key)) buffer += e.key; else if (e.key === 'Enter' && buffer.length >= 8) { e.preventDefault(); void addByBarcode(buffer); buffer = '' } } window.addEventListener('keydown', onKey); return () => window.removeEventListener('keydown', onKey) }, [screen, scannerOpen])
  useEffect(() => () => window.clearTimeout(toastTimer.current), [])

  function chooseMode(value: Mode) { setMode(value) }
  function chooseCadence(value: Cadence) { setCadence(value) }
  function continueFromMode() { if (!mode || !cadence) return; if (mode === 'individual') { setMembers([initialMember]); setScreen('profiles') } else setScreen('count') }
  function chooseCount(value: number) { setCount(value); setMembers(Array.from({ length: value }, (_, i) => ({ ...initialMember, id: i + 1, name: i === 0 ? 'You' : `Person ${i + 1}` }))); setScreen('profiles') }
  function updateMember(patch: Partial<Member>) { setMembers(prev => prev.map((m, i) => i === activeMember ? { ...m, ...patch } : m)) }
  function beginCalculation() { setScreen('calculating'); window.setTimeout(() => setScreen('cart'), 1300) }
  function showToast(text: string, tone: 'ok' | 'warn' = 'ok') { window.clearTimeout(toastTimer.current); setToast({ text, tone }); toastTimer.current = window.setTimeout(() => setToast(null), 2600) }
  function addProduct(product: Product, silent = false) { const key = productKey(product); setCart(prev => prev.some(x => productKey(x) === key) ? prev.map(x => productKey(x) === key ? { ...x, quantity: x.quantity + 1 } : x) : [{ ...product, quantity: 1 }, ...prev]); if (!silent) showToast(`${product.name} added to cart`) }
  async function addByBarcode(code: string) { const result = await lookupProduct(code); if (result.status === 'found') addProduct(result.product); else showToast(result.status === 'not-found' ? `No product found for ${code}` : result.message, 'warn') }
  function openScanner() { primeScannerFeedback(); setScannerOpen(true) }
  function adjust(key: string, amount: number) { setCart(prev => prev.map(x => productKey(x) === key ? { ...x, quantity: Math.max(0, x.quantity + amount) } : x).filter(x => x.quantity > 0)) }
  function finishShopping() { if (!cart.length) { showToast('Scan at least one item before finishing.', 'warn'); return } setScannerOpen(false); setCelebrating(true) }
  function reset() { setCelebrating(false); setScannerOpen(false); setScreen('mode'); setMode(null); setCadence(null); setCart([]); setMembers([initialMember]); setActiveMember(0) }

  if (screen === 'calculating') return <main className="app-shell center-screen"><Logo /><div className="calculation"><div className="pulse-ring"><Sparkles size={34} /></div><h1>Making your family plan</h1><p>Balancing nutrients for {members.length} {members.length === 1 ? 'person' : 'people'}...</p><div className="loading-line"><span /></div></div></main>
  return <main className="app-shell"><header><Logo /><Stepper step={screen === 'cart' ? 3 : screen === 'mode' || screen === 'count' ? 1 : 2} /><button className="icon-button" onClick={reset} aria-label="Start over"><RotateCcw size={19} /></button></header>
    {screen === 'mode' && <section className="screen intro-screen"><div className="eyebrow">SMART SHOPPING, SIMPLIFIED</div><h1>Let&apos;s plan a <em>healthier</em><br />cart together.</h1><p className="lead">Tell us who you&apos;re shopping for. We&apos;ll calculate the right balance of nutrients for your household.</p><div className="mode-grid"><button className={`mode-card ${mode === 'individual' ? 'selected' : ''}`} onClick={() => chooseMode('individual')}><div className="mode-visual single"><UserRound /></div><strong>Just me</strong><span>Personal nutrition targets</span><ArrowRight /></button><button className={`mode-card ${mode === 'family' ? 'selected' : ''}`} onClick={() => chooseMode('family')}><div className="mode-visual family"><Users /></div><strong>My family</strong><span>Plan for everyone at home</span><ArrowRight /></button></div><div className="cadence-choice"><div className="cadence-label">Shopping for</div><div className="cadence-toggle"><button className={cadence === 'weekly' ? 'active' : ''} onClick={() => chooseCadence('weekly')}>Weekly</button><button className={cadence === 'monthly' ? 'active' : ''} onClick={() => chooseCadence('monthly')}>Monthly</button></div></div><button className="primary-action intro-continue" disabled={!mode || !cadence} onClick={continueFromMode}>Continue <ArrowRight size={18} /></button><p className="hint"><CircleHelp size={15} /> You can always change this later</p><AndroidAppLink /></section>}
    {screen === 'count' && <section className="screen narrow-screen"><button className="back-link" onClick={() => setScreen('mode')}><ArrowLeft size={16} /> Back</button><div className="eyebrow">HOUSEHOLD SETUP</div><h1>How many people<br />are you feeding?</h1><p className="lead">We&apos;ll tailor the nutrition goals to everyone in your household.</p><div className="number-pad">{[1, 2, 3, 4, 5, 6, 7, 8, 9, 10].map(n => <button className={count === n ? 'selected' : ''} onClick={() => setCount(n)} key={n}>{n}</button>)}</div><button className="primary-action" onClick={() => chooseCount(count)}>Continue <ArrowRight size={18} /></button></section>}
    {screen === 'profiles' && <section className="screen profiles-screen"><button className="back-link" onClick={() => setScreen(mode === 'family' ? 'count' : 'mode')}><ArrowLeft size={16} /> Back</button><div className="eyebrow">PERSON {activeMember + 1} OF {members.length}</div><h1>Tell us about<br /><em>{current.name}</em>.</h1><div className="profile-layout"><div className="profile-card"><div className="profile-top"><button className="round-arrow" onClick={() => setActiveMember((activeMember - 1 + members.length) % members.length)}><ChevronLeft /></button><div className="silhouette"><Silhouette member={current} /></div><button className="round-arrow" onClick={() => setActiveMember((activeMember + 1) % members.length)}><ChevronRight /></button></div><div className="dots">{members.map((m, i) => <button aria-label={`Person ${i + 1}`} className={i === activeMember ? 'on' : ''} onClick={() => setActiveMember(i)} key={m.id} />)}</div></div><div className="form-panel"><label>Name<input value={current.name} onChange={e => updateMember({ name: e.target.value })} /></label><div className="field-row"><label>Age<input type="number" min="1" max="120" value={current.age} onChange={e => updateMember({ age: Number(e.target.value) })} /></label><label>Body type<div className="segmented"><button className={current.type === 'Adult' ? 'active' : ''} onClick={() => updateMember({ type: 'Adult' })}>Adult</button><button className={current.type === 'Child' ? 'active' : ''} onClick={() => updateMember({ type: 'Child' })}>Child</button></div></label></div><label>Height <b>{current.height} cm</b><input className="range" type="range" min="90" max="220" value={current.height} onChange={e => updateMember({ height: Number(e.target.value) })} /></label><label>Weight <b>{current.weight} kg</b><input className="range" type="range" min="20" max="180" value={current.weight} onChange={e => updateMember({ weight: Number(e.target.value) })} /></label><label>Body size <b>{SILHOUETTE_LEVELS[current.sizeStep - 1]}</b><input className="range size-range" type="range" min="1" max="5" step="1" value={current.sizeStep} onChange={e => updateMember({ sizeStep: Number(e.target.value) })} /></label><label>Gender<div className="segmented"><button className={current.gender === 'Female' ? 'active' : ''} onClick={() => updateMember({ gender: 'Female' })}>Female</button><button className={current.gender === 'Male' ? 'active' : ''} onClick={() => updateMember({ gender: 'Male' })}>Male</button></div></label></div></div><button className="primary-action profile-next" onClick={() => activeMember < members.length - 1 ? setActiveMember(activeMember + 1) : beginCalculation()}>{activeMember < members.length - 1 ? 'Next person' : 'Calculate our plan'} <ArrowRight size={18} /></button></section>}
    {screen === 'cart' && <section className="screen cart-screen"><div className="cart-heading"><div><div className="eyebrow">YOUR SMART CART</div><button className="cadence-pill" onClick={() => setScreen('mode')}>Calendar {cadence === 'monthly' ? 'Monthly' : 'Weekly'} Plan</button><h1>Good choices start{' '}<br />with <em>good balance.</em></h1><p className="lead">Scan an item to see how it helps your household goals.</p></div><button className="scan-button" onClick={openScanner}><ScanLine size={25} /><span>Scan item</span><small>Camera or barcode gun</small></button></div><div className="cart-grid"><div className="goals-card"><div className="card-title"><span>Household progress</span><span className="people-pill"><Users size={14} /> {members.length} {members.length === 1 ? 'person' : 'people'}</span></div>{NUTRIENTS.map(({ label, key, unit, color }) => { const pct = targets[key] ? consumed[key] / targets[key] * 100 : 0; return <div className={`goal-row ${pct > 100 ? 'over' : ''}`} key={key}><div className="goal-label"><span>{label} <i>{Math.round(pct)}%</i></span><b>{Math.round(consumed[key]).toLocaleString()} <small>/ {targets[key].toLocaleString()} {unit}</small></b></div><ProgressBar color={color} value={pct} /></div> })}</div><div className="items-card"><div className="card-title"><span>Scanned items</span><span className="item-count">{cart.reduce((a, x) => a + x.quantity, 0)} {cart.reduce((a, x) => a + x.quantity, 0) === 1 ? 'item' : 'items'}</span></div>{cart.length === 0 ? <div className="empty-cart"><div><Radio size={29} /><span>Ready when you are</span></div><p>Scan your first item to start building a balanced cart.</p></div> : <div className="items-list">{cart.map(item => { const key = productKey(item); return <div className="item-row" key={key}><div className="food-dot" style={{ background: item.accent }}>{item.image_url && <img src={item.image_url} alt="" loading="lazy" />}</div><div className="item-name"><b>{item.name}</b><small>{[item.brand, item.serving_size, `${Math.round(item.calories * item.quantity).toLocaleString()} kcal`].filter(Boolean).join(' · ')}</small></div><div className="quantity"><button onClick={() => adjust(key, -1)} aria-label={`One less ${item.name}`}><Minus size={14} /></button><b>{item.quantity}</b><button onClick={() => adjust(key, 1)} aria-label={`One more ${item.name}`}><Plus size={14} /></button></div><button className="remove" onClick={() => adjust(key, -item.quantity)} aria-label={`Remove ${item.name}`}><Trash2 size={16} /></button></div> })}</div>}</div></div>{toast && <div className={`toast ${toast.tone}`} role="status">{toast.tone === 'ok' ? <Check size={16} /> : <TriangleAlert size={16} />} {toast.text}</div>}<button className="finish-button" onClick={finishShopping}>Finish shopping <Check size={18} /></button></section>}
    {celebrating && <FinishCelebration cart={cart} consumed={consumed} targets={targets} people={members.length} periodLabel={cadence === 'monthly' ? 'monthly' : 'weekly'} onNewCart={reset} onKeepShopping={() => setCelebrating(false)} />}
    {scannerOpen && <BarcodeScanner cart={cart} targets={targets} periodLabel={cadence === 'monthly' ? 'monthly' : 'weekly'} onAdd={product => addProduct(product, true)} onUndo={product => adjust(productKey(product), -1)} onClose={() => setScannerOpen(false)} />}
  </main>
}
